services:
  cam1:
    image: beholderrpa/ustreamer:latest
    platform: linux/arm64
    container_name: ustreamer-cam1
    restart: unless-stopped
    devices:
      - "${CAM1_DEVICE}:/dev/video0"
    command:
      - "--device=/dev/video0"
      - "--host=0.0.0.0"
      - "--port=8080"
      - "--resolution=${CAM1_RESOLUTION}"
      - "--desired-fps=${CAM1_FPS}"
      - "--format=JPEG"
      - "--persistent"
#      - "--drop-same-frames=30"
    ports:
      - "8081:8080"

  cam2:
    image: beholderrpa/ustreamer:latest
    platform: linux/arm64
    container_name: ustreamer-cam2
    restart: unless-stopped
    devices:
      - "${CAM2_DEVICE}:/dev/video0"
    command:
      - "--device=/dev/video0"
      - "--host=0.0.0.0"
      - "--port=8080"
      - "--resolution=${CAM2_RESOLUTION}"
      - "--desired-fps=${CAM2_FPS}"
      - "--format=JPEG"
      - "--persistent"
#      - "--drop-same-frames=30"
    ports:
      - "8082:8080"
      
  cam3:
    image: beholderrpa/ustreamer:latest
    platform: linux/arm64
    container_name: ustreamer-cam3
    restart: unless-stopped
    devices:
      - "${CAM3_DEVICE}:/dev/video0"
    command:
      - "--device=/dev/video0"
      - "--host=0.0.0.0"
      - "--port=8080"
      - "--resolution=${CAM3_RESOLUTION}"
      - "--desired-fps=${CAM3_FPS}"
      - "--format=JPEG"
      - "--persistent"
#      - "--drop-same-frames=30"
    ports:
      - "8083:8080"


  web:
    image: nginx:alpine
    container_name: schweini-web
    restart: unless-stopped
    depends_on:
      - cam1
      - cam2
      - cam3
    ports:
      - "8090:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
